from __future__ import annotations

import re
from pathlib import Path
from typing import Any


def _last_int(pattern: str, text: str) -> int | None:
    matches = re.findall(pattern, text, flags=re.MULTILINE)
    if not matches:
        return None
    return int(matches[-1])


def _last_float(pattern: str, text: str) -> float | None:
    matches = re.findall(pattern, text, flags=re.MULTILINE)
    if not matches:
        return None
    return float(matches[-1])


def _first_text(pattern: str, text: str) -> str | None:
    match = re.search(pattern, text, flags=re.MULTILINE)
    if match is None:
        return None
    return match.group(1).strip()


def parse_result_file(path: Path) -> dict[str, Any]:
    """Parse one ict_pcg output file generated by the demo runner."""

    text = path.read_text(encoding="utf-8", errors="replace")
    pcg_time_s = _last_float(r"PCG time:\s*([0-9.eE+-]+)\s*seconds", text)
    exception = _first_text(r"Exception:\s*(.+)", text)

    metrics: dict[str, Any] = {
        "raw_path": str(path),
        "pcg_iterations": _last_int(r"PCG iterations=([0-9]+)", text)
        or _last_int(r"Iterations taken by PCG:\s*([0-9]+)", text),
        "final_residual": _last_float(r"finalRes=([0-9.eE+-]+)", text),
        "sptrsv_avg_time_ms": _last_float(r"avg_sptrsv_ms=([0-9.eE+-]+)", text),
        "pcg_time_s": pcg_time_s,
        "pcg_time_ms": pcg_time_s * 1000.0 if pcg_time_s is not None else None,
        "relative_residual": _last_float(
            r"relative residual of the scaled linear system.*:\s*([0-9.eE+-]+)", text
        ),
        "nnz_l": _last_int(r"nnz of L\s*:\s*([0-9]+)", text),
        "exception": exception,
        "num_supernodes": _last_int(r"num_supernodes=([0-9]+)", text),
        "packed_dense_slots": _last_int(r"packed_dense_slots=([0-9]+)", text),
        "solve_dependency_levels": _last_int(r"solve_dependency_levels=([0-9]+)", text),
        "max_solve_bucket_size": _last_int(r"max_solve_bucket_size=([0-9]+)", text),
        "supernode_block_density": _last_float(r"supernode_block_density=([0-9.eE+-]+)", text),
    }
    return metrics
