# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /tmp/ic

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /tmp/ic

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /tmp/ic/CMakeFiles /tmp/ic//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /tmp/ic/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /tmp/ic/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ichol

# Build rule for target.
ichol: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ichol
.PHONY : ichol

# fast build rule for target.
ichol/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/ichol.dir/build.make src/CMakeFiles/ichol.dir/build
.PHONY : ichol/fast

#=============================================================================
# Target rules for targets named ict_pcg

# Build rule for target.
ict_pcg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ict_pcg
.PHONY : ict_pcg

# fast build rule for target.
ict_pcg/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/ict_pcg.dir/build.make src/CMakeFiles/ict_pcg.dir/build
.PHONY : ict_pcg/fast

#=============================================================================
# Target rules for targets named test_io

# Build rule for target.
test_io: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_io
.PHONY : test_io

# fast build rule for target.
test_io/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_io.dir/build.make test/CMakeFiles/test_io.dir/build
.PHONY : test_io/fast

#=============================================================================
# Target rules for targets named test_fact

# Build rule for target.
test_fact: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_fact
.PHONY : test_fact

# fast build rule for target.
test_fact/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_fact.dir/build.make test/CMakeFiles/test_fact.dir/build
.PHONY : test_fact/fast

#=============================================================================
# Target rules for targets named test_cg

# Build rule for target.
test_cg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_cg
.PHONY : test_cg

# fast build rule for target.
test_cg/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_cg.dir/build.make test/CMakeFiles/test_cg.dir/build
.PHONY : test_cg/fast

#=============================================================================
# Target rules for targets named test_ic

# Build rule for target.
test_ic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ic
.PHONY : test_ic

# fast build rule for target.
test_ic/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_ic.dir/build.make test/CMakeFiles/test_ic.dir/build
.PHONY : test_ic/fast

#=============================================================================
# Target rules for targets named test_symbolic

# Build rule for target.
test_symbolic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_symbolic
.PHONY : test_symbolic

# fast build rule for target.
test_symbolic/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_symbolic.dir/build.make test/CMakeFiles/test_symbolic.dir/build
.PHONY : test_symbolic/fast

#=============================================================================
# Target rules for targets named test_supernodal

# Build rule for target.
test_supernodal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_supernodal
.PHONY : test_supernodal

# fast build rule for target.
test_supernodal/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_supernodal.dir/build.make test/CMakeFiles/test_supernodal.dir/build
.PHONY : test_supernodal/fast

#=============================================================================
# Target rules for targets named test_sptrsv

# Build rule for target.
test_sptrsv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_sptrsv
.PHONY : test_sptrsv

# fast build rule for target.
test_sptrsv/fast:
	$(MAKE) $(MAKESILENT) -f test/CMakeFiles/test_sptrsv.dir/build.make test/CMakeFiles/test_sptrsv.dir/build
.PHONY : test_sptrsv/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ichol"
	@echo "... ict_pcg"
	@echo "... test_cg"
	@echo "... test_fact"
	@echo "... test_ic"
	@echo "... test_io"
	@echo "... test_sptrsv"
	@echo "... test_supernodal"
	@echo "... test_symbolic"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /tmp/ic/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

